# Generated by Django 4.1.5 on 2023-02-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=20, unique=True)),
                ('publisher_contact', models.CharField(max_length=300)),
                ('book_label_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_desc', models.CharField(max_length=300)),
                ('book_genre', models.CharField(max_length=30)),
                ('book_publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publishers')),
            ],
        ),
    ]
