# Generated by Django 4.1.5 on 2023-02-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishers',
            old_name='book_label_address',
            new_name='publisher_address',
        ),
    ]
