# Generated by Django 4.1.5 on 2023-02-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('author_address', models.CharField(max_length=300)),
                ('author_contact', models.CharField(max_length=30)),
            ],
        ),
    ]
